### ISSUE TITLE
managing output of the .tpa files 

### ISSUE THREAD

**Issue by vbakayov** [phenology/platform-for-pheno-products#17]
EDIT: I  can  first union all the output from the .tpa files in order not work at tile level and build the tiff as you demonstrated , and then reload into the TileLayerRDDs all the seasons. Maybe that would be easier.

To get the (x,y,value) on the original .tiff I must load it as RasterExtent ? Will try tomorrow

===================================================
geotrellis can be what we need to organize our output of the tiles.

Tiles can be 'stitched' into a single tiff with similar to this example code:
http://geotrellis.readthedocs.io/en/latest/guide/spark.html#stiching-tiles-into-a-single-geotiff . This requires RDD[(ProjectedExtent, Tile)]

and can be organized in TileLayerRDDs for easy management. They are organized on grids or  cubes with the help of SpatialKey or SpaceTimeKey.

 We can create a tile from a single .tpa file  output with DoubleArrayTile(array, dimX, dimY).

However, all this to work a tile must  know its projection (CRS) and its extend. 

 Then we can create both RDD[(ProjectedExtent, Tile)] or TileLayerRDDs  similarly as shown here : https://media.readthedocs.org/pdf/geotrellis/latest/geotrellis.pdf  (page:154 ;3.18.3 Create a Layer from a single Tile).

Is this a good approach ? I guess the projection is all the same for all tiles, but can we calculate the extend  for each tile based on the pixel range we have ?

**Comment by romulogoncalves** [comment]
"Is this a good approach ? I guess the projection is all the same for all tiles, but can we calculate the extend for each tile based on the pixel range we have ?"

The projection is the same for all tiles. The extend is the bounding box of each Tile, this is, the min x, min y, max x and max y. Such values are known from the cropping phase.

**Comment by vbakayov** [comment]
The implementation was to gather all pixel values for a corresponding season, union with original values (keep NaNs, if pheno_value -> use it if not place Nan), keep the projections of original tif and reconstruct the picture
