### ISSUE TITLE
First .tif USA produced !

### ISSUE THREAD

**Issue by vbakayov** [phenology/platform-for-pheno-products#19]
Hi,

Good news ! I managed to produce the first USA SOS .tif today.  You can download it here : https://uploadfiles.io/xzzke 

It is for the second season for the time interval I've selected.

Still, there I have few issues/questions : 
1.  It is possible that there is no (x,y) pair produced from TimeSat, but there is an NDVI value for the same x,y in the template I use (check upper-middle region of tif). Currently I just use the NDVI value, but to what value should I set those pixels ?

2. It is possible that there are (x,y) pairs produced from TimeSat, but all seasonality metrics are 0 . What does this mean ? 

3.  The  SOS values are as produced from TimeSat. They are floats with 14-digits of precision. (example: 79.97162628173828). This makes the compression to perform not so great (40 MB file). How many values after the dot is reasonable to have  without loosing precision ? 

4. I am not understanding what the exact  SOS value represents, is it day/file number/week ?  Also the values are from the beginning of the time series, rather from the beginning  of the year. The years, except the first must be off-set by some value * index of season. What such a value would be ?

**Comment by romulogoncalves** [comment]
@rzuritamilla I think here your knowledge with TimeSat would be valuable.

**Comment by vbakayov** [comment]
Here are my suggestions.
1. This is most likely caused by too many constant/missing data. My intuition is to set the pixel to "no data" which in geotrellis DoubleArrayTile is Double.NaN
2. No idea why such a behavior, but might be used just as an empty placeholder if the number of seasons produced is constant per pixel pair. Such observations, however were negligible. 

3 and 4 : The seasonality value represents the file number in the sequence. This dataset is of decadal composits starting from 1998-04-01. We can calculate the number of days passed based on the file index and when added to the starting date will sum up to the date of the SOS. The number of dates passed can be derived by  rounding the (file_number to the first significant number  -1) *10  (assuming daily ground  observation precision) Therefore, we can lose all subsequent higher precision digits. 
As geotiff encodes the pixel values as just ... well values I intend to calculate the exact date when time for comparison. Or it might the case dates are aligned to this model.

**Comment by rzuritamilla** [comment]
Sorry for my delayed reaction. These are crazy weeks. I was sick and then i had to deal with a few urgent issues at ITC. Tomorrow I fly to Vienna for the EGU conference.
I think that i need a bit of additional info (and possibly a couple of days to think about this)

- what do you mean by "for the second season"?  
are you trying to model more than one vegetation season per year or you just simply mean that these results correspond to the 2nd year of the time series.

1. if you have NDVI values you should get an output. Unless there are too many missing or constant values and then the curve fitting fails... 
2. this is weird. if these are not seasonality metrics, what are the x,y pairs produced by timesat then?
3 and 4. your explanation sounds very plausible. I could check this beginning of next week. OK?

**Comment by vbakayov** [comment]
Hi Raul,

No worries, I was in Vienna this winter, wonderful city !

When I say 2nd season is the 2nd year in the time series, therefor 1
vegetational season per year .

1. yes, I think that is what is happening, the GUI says too many constant
data or  missing pixels (if I run on a water region ). It is a big region
in Canada what  it fails. I think there might be a lot of missing data due
to clouds.
2. I manually observed few million of pairs and this only happens 20-30
times in the  most top-left region for either the 7th or 8th season.

I am starting the try to compare the ground observations with the geotif. I
will ask  questions in the Slack group Romulo created.  Do you get
notifications from there ?

Best,
Viktor

**Comment by romulogoncalves** [comment]
In case Raul does get notifications, just to
@Raul and he will get an email if does not answer your messages
Romulo

________________________________________

**Comment by vbakayov** [comment]
The mentioned points above are much clear now 
1. if no value , replace with NaN 
2.0s  are used as a placeholder if TimeSat can't find a fit for the corresponding year
3. Round to 1 digit of precision to get the exact day
4. It if file number in the sequence
